version: '3.8'

services:
  db:
    image: postgres:16.4-alpine3.19
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    secrets:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASS
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_NAME
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASS
    env_file:
      - dev.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - shortener_net

  main-app:
    image: shrtnr_main:${IMAGE_TAG}
    depends_on:
      - db
    env_file:
      - dev.env
    secrets:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASS
    ports:
      - ${PORT}:${PORT}
    networks:
      - shortener_net
    command: ["/app/main"]

  redir-app:
    image: shrtnr_redir:${IMAGE_TAG}
    depends_on:
      - db
    env_file:
      - dev.env
    secrets:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASS
    ports:
      - ${PORT_SHORTEN}:${PORT_SHORTEN}
    networks:
      - shortener_net
    command: ["/app/red"]

volumes:
  db-data:
    driver: local

networks:
  shortener_net:
    driver: overlay

secrets:
  POSTGRES_PASS:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_NAME:
    external: true
